# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Medium follower count
  - MediumFollowersCountPlugin:
      username: ppristas
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - ppristas/ZMarkupParser
      - ppristas/ZReviewTender
      - ppristas/ZMediumToMarkdown
      - ppristas/linkyee

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "Love's Lore Court Links"

# Avatar image path
avatar: "./images/profile.jpg"

# Name section text
name: "@loveslorecourt"

# Tagline section text
tagline: >-
    záložky, knižní svíčky, zážitkové tematické knižní boxy

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-solid fa-heart"
      text: "hlavní stránka LLC"
      url: "https://www.loveslorecourt.cz/"
      alt: "Love's Lore Court Hlavní stránka"
      title: "Love's Lore Court Hlavní stránka"
      target: "_blank"
      
  - link:
      icon: "custom-icon custom-mystery-box"
      text: "Mystery boxy"
      url: "https://www.loveslorecourt.cz/box"
      alt: "Love's Lore Court Mystery box"
      title: "Love's Lore Court Mystery box"
      target: "_blank"

  - link:
      icon: "custom-icon"
      text: "Rande s knihou"
      url: "https://www.loveslorecourt.cz/blind-date"
      alt: "Love's Lore Court Rande s knihou"
      title: "Love's Lore Court Rande s knihou"
      target: "_blank"

  - link:
      icon: "custom-icon custom-knihomol"
      text: "Knihomolské doplňky"
      url: "https://www.loveslorecourt.cz/knizni-doplnky"
      alt: "Love's Lore Court Knihomolské doplňky"
      title: "Love's Lore Court Knihomolské doplňky"
      target: "_blank"

# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/loveslorecourt/"
      title: "Instagram"
      alt: "Love's Lore Court Instagram"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:info@loveslorecourt.com"
      title: "Email: info@loveslorecourt.com"
      alt: "info@loveslorecourt.com"
      target: "_blank"

# Footer text
footer: >
    Hi there! Follow me or stay connected on Instagram.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2025  <a href="https://loveslorecourt.cz" target="_blank">loveslorecourt</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
